version: "0"
services:
  leaguebot:
    build:
      context: .
      dockerfile: Dockerfile
    image: long-horns
    container_name: long-horns
    volumes:
      - .:/services
    depends_on:
      - sqlitedb
  sqlitedb:
    image: nouchka/sqlite3:latest
    volumes:
      - ${SQLITE3_PATH}:/root/db
    environment:
      - SQLITE3_DB=${SQLITE3_DB_FILE}

volumes:
  sqlite-data:
